use_frameworks!

platform :ios, '8.0'

target 'HypersMobileAnalyticsSDK_Example' do
  pod 'HypersMobileAnalyticsSDK', :path => '../'

  target 'HypersMobileAnalyticsSDK_Tests' do
    inherit! :search_paths

    pod 'Specta'
    pod 'Expecta'
    pod 'FBSnapshotTestCase'
    pod 'Expecta+Snapshots'
  end
end
